# Generated by Django 2.0.6 on 2018-06-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
