# Generated by Django 2.0.6 on 2018-06-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gneissest_rocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rocks',
            new_name='Rock',
        ),
    ]
